import { useCatalogue } from "../../state/CatalogueContext.jsx";
import RevealSection from "../../components/RevealSection.jsx";
import { motion } from "motion/react";


export default function Section07CalibreCertified() {
  const ui = useCatalogue();
  return (<RevealSection className="grid grid-cols-1 md:grid-cols-4 gap-space-md p-space-lg bg-surface-container-low rounded-xl"><div className="flex items-start gap-space-sm"><div className="w-10 h-10 rounded-lg bg-surface-container-lowest text-secondary flex items-center justify-center shrink-0 shadow-sm"><span className="material-symbols-outlined text-[24px]">{"verified"}</span></div><div><h4 className="font-label-md text-label-md uppercase tracking-wider font-bold mb-1">{"Calibre Certified"}</h4><p className="font-body-sm text-body-sm text-on-surface-variant">{"Inspected on Witschi timing machines for +/- 4s precision daily."}</p></div></div><div className="flex items-start gap-space-sm"><div className="w-10 h-10 rounded-lg bg-surface-container-lowest text-secondary flex items-center justify-center shrink-0 shadow-sm"><span className="material-symbols-outlined text-[24px]">{"shield_with_heart"}</span></div><div><h4 className="font-label-md text-label-md uppercase tracking-wider font-bold mb-1">{"Armored Transit"}</h4><p className="font-body-sm text-body-sm text-on-surface-variant">{"Full-valuation Lloyds insured delivery in tamper-evident steel lockbox."}</p></div></div><div className="flex items-start gap-space-sm"><div className="w-10 h-10 rounded-lg bg-surface-container-lowest text-secondary flex items-center justify-center shrink-0 shadow-sm"><span className="material-symbols-outlined text-[24px]">{"published_with_changes"}</span></div><div><h4 className="font-label-md text-label-md uppercase tracking-wider font-bold mb-1">{"7-Day Inspection"}</h4><p className="font-body-sm text-body-sm text-on-surface-variant">{"Wear in your sanctuary. Unconditional return if escapement fails your standard."}</p></div></div><div className="flex items-start gap-space-sm"><div className="w-10 h-10 rounded-lg bg-surface-container-lowest text-secondary flex items-center justify-center shrink-0 shadow-sm"><span className="material-symbols-outlined text-[24px]">{"workspace_premium"}</span></div><div><h4 className="font-label-md text-label-md uppercase tracking-wider font-bold mb-1">{"5-Year Atelier Care"}</h4><p className="font-body-sm text-body-sm text-on-surface-variant">{"Comprehensive mechanical movement guarantee and gasket recalibration."}</p></div></div></RevealSection>);
}
