export default {
        content: ["./index.html", "./src/**/*.{js,jsx}"],
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "surface-container-lowest": "#ffffff",
              "outline-variant": "#c2c6d5",
              "on-secondary-fixed-variant": "#7f2b00",
              "on-secondary-fixed": "#370e00",
              "error-container": "#ffdad6",
              "surface-dim": "#dbd9e0",
              "primary-container": "#0056c3",
              "error": "#ba1a1a",
              "on-primary": "#ffffff",
              "on-primary-fixed": "#001944",
              "on-primary-fixed-variant": "#004299",
              "primary": "#004094",
              "on-secondary": "#ffffff",
              "surface-container-high": "#e9e7ee",
              "inverse-primary": "#afc6ff",
              "tertiary-fixed-dim": "#ffb866",
              "tertiary": "#643b00",
              "on-error-container": "#93000a",
              "surface-tint": "#0959c6",
              "surface-container-low": "#f4f3fa",
              "on-tertiary-fixed-variant": "#673d00",
              "surface-container": "#efedf4",
              "secondary-fixed": "#ffdbce",
              "on-secondary-container": "#571b00",
              "surface-variant": "#e3e1e8",
              "tertiary-fixed": "#ffddba",
              "on-tertiary": "#ffffff",
              "secondary-fixed-dim": "#ffb599",
              "primary-fixed": "#d9e2ff",
              "surface-bright": "#faf8ff",
              "secondary-container": "#fd661d",
              "on-error": "#ffffff",
              "surface": "#faf8ff",
              "primary-fixed-dim": "#afc6ff",
              "outline": "#737785",
              "on-background": "#1a1b20",
              "inverse-surface": "#2f3035",
              "inverse-on-surface": "#f2f0f7",
              "on-tertiary-fixed": "#2b1700",
              "on-surface-variant": "#424753",
              "background": "#faf8ff",
              "surface-container-highest": "#e3e1e8",
              "on-tertiary-container": "#ffcb94",
              "tertiary-container": "#845000",
              "on-primary-container": "#c4d4ff",
              "secondary": "#a63b00",
              "on-surface": "#1a1b20"
            },
            borderRadius: {
              DEFAULT: "0.25rem",
              lg: "0.5rem",
              xl: "0.75rem",
              full: "9999px"
            },
            spacing: {
              "space-lg": "2rem",
              "space-xs": "0.5rem",
              gutter: "1.5rem",
              "space-sm": "1rem",
              "margin-mobile": "1rem",
              margin: "2rem",
              "space-md": "1.5rem",
              "space-xl": "3rem",
              "gutter-sm": "1rem"
            },
            fontFamily: {
              "body-sm": ["Manrope"],
              "title-editorial": ["Manrope"],
              "display-hero": ["Manrope"],
              "label-caps": ["Manrope"],
              "body-lg": ["Manrope"],
              "headline-lg": ["Manrope"],
              "numeric-price": ["Manrope"],
              "display-hero-mobile": ["Manrope"],
              "headline-lg-mobile": ["Manrope"],
              "body-md": ["Manrope"],
              "label-md": ["Manrope"],
              "headline-md": ["Manrope"],
              "headline-sm": ["Manrope"]
            },
            fontSize: {
              "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" }],
              "title-editorial": ["18px", { lineHeight: "26px", letterSpacing: "0.01em", fontWeight: "500" }],
              "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
              "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
              "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
              "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
              "numeric-price": ["22px", { lineHeight: "26px", letterSpacing: "-0.02em", fontWeight: "700" }],
              "display-hero-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.025em", fontWeight: "800" }],
              "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "700" }],
              "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
              "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "600" }],
              "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
              "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }]
            }
          }
        }
      };
