import { useCatalogue } from "../../state/CatalogueContext.jsx";
import RevealSection from "../../components/RevealSection.jsx";
import { motion } from "motion/react";
export default function Section03AsterNo04Automatic() {
  const ui = useCatalogue();
  return <RevealSection className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-space-lg mb-space-xl"><motion.article className={ui.productClass("bg-surface-container-lowest rounded-xl shadow-sm hover:shadow-xl transition-all duration-300 flex flex-col group overflow-hidden", "Aster No.04 Automatic — Midnight Edition", "Midnight Edition Swiss Sellita SW200-1 favorite lightbulb Super-LumiNova BGW9 visibility Quick View Aster Horology Ref. AT-04-NOCT Aster No.04 Automatic — Midnight Edition Deep matte black dial paired with brushed DLC carbon casing. Skeletonized sapphire exhibition caseback displaying precision rotor. Calibre Auto 28.8k Power 38 Hours Depth 100m ATM Atelier Value ₹18,990 shopping_bag Acquire", "", "")} style={{
      order: ui.sortOrder(18990, 1)
    }} whileHover={{
      y: -4
    }} transition={{
      type: "spring",
      stiffness: 300,
      damping: 26
    }} data-product-link="true" role="link" tabIndex={0}><div className="relative bg-surface-container-low p-space-lg flex items-center justify-center min-h-[320px] overflow-hidden"><div className="absolute top-space-md left-space-md flex flex-col gap-1 z-10"><span className="px-2.5 py-0.5 rounded bg-primary text-secondary-fixed font-label-sm text-label-sm uppercase tracking-wider">{"Midnight Edition"}</span><span className="px-2 py-0.5 rounded bg-surface-container-lowest text-on-surface-variant font-label-sm text-label-sm uppercase tracking-wider shadow-sm">{"Swiss Sellita SW200-1"}</span></div><button type="button" aria-label="Save to Vault" className="absolute top-space-md right-space-md w-9 h-9 rounded-full bg-surface-container-lowest/80 backdrop-blur-sm text-on-surface-variant hover:text-error hover:bg-surface-container-lowest flex items-center justify-center transition-all z-10 shadow-sm" onClick={() => ui.toggleWishlist("Aster No.04 Automatic — Midnight Edition")}><span className="material-symbols-outlined text-[20px]">{"favorite"}</span></button><img className="w-64 h-64 object-contain group-hover:scale-105 transition-transform duration-500" alt="Aster No 04 Automatic luxury watch, midnight black sunburst dial with luminous indices, DLC black coated stainless steel 41mm case, sapphire crystal reflection, premium black horween leather strap, isolated high-end watch photography, pure white background." data-alt="Aster No 04 Automatic luxury watch, midnight black sunburst dial with luminous indices, DLC black coated stainless steel 41mm case, sapphire crystal reflection, premium black horween leather strap, isolated high-end watch photography, pure white background." src="https://lh3.googleusercontent.com/aida-public/AB6AXuADdVXE9HfNLIRo4WjadNZiSuSNUrg3NETgVNpbCdhR0fR3tBWseYP2zn5pG0T2YJREOE7uMFVQFoyummpH34y_1SFK-l-4NGVgxyXDetQkOC3175aH-WpqJ1g_oQSih3OSgXe0qp_9svaSGd0cmc2gtMDeUoVqpbqfjRiAvrKw9jUYCFcPsJHzjyskzdmihSJfSFieG7cQtdfQAjcGSZrJw9hW1hV8zblekk14PwyHj0MjNucnK0oX" /><div className="absolute bottom-space-md left-space-md px-2 py-1 rounded bg-primary/90 text-tertiary-fixed font-label-sm text-label-sm uppercase flex items-center gap-1"><span className="material-symbols-outlined text-[13px]">{"lightbulb"}</span>{"\n              Super-LumiNova BGW9\n            "}</div><button type="button" className="absolute bottom-space-md right-space-md h-8 px-space-sm rounded bg-surface-container-lowest/90 backdrop-blur-sm hover:bg-primary hover:text-surface-container-lowest font-label-sm text-label-sm uppercase tracking-wider transition-all flex items-center gap-1 shadow-sm" onClick={() => ui.openQuickView({
          "title": "Aster No.04 Automatic",
          "price": "₹18,990",
          "series": "Midnight Edition",
          "specs": "Sellita SW200-1 Automatic • 41mm DLC Case • 38h Reserve",
          "image": "https://lh3.googleusercontent.com/aida-public/AB6AXuADdVXE9HfNLIRo4WjadNZiSuSNUrg3NETgVNpbCdhR0fR3tBWseYP2zn5pG0T2YJREOE7uMFVQFoyummpH34y_1SFK-l-4NGVgxyXDetQkOC3175aH-WpqJ1g_oQSih3OSgXe0qp_9svaSGd0cmc2gtMDeUoVqpbqfjRiAvrKw9jUYCFcPsJHzjyskzdmihSJfSFieG7cQtdfQAjcGSZrJw9hW1hV8zblekk14PwyHj0MjNucnK0oX"
        })}><span className="material-symbols-outlined text-[15px]">{"visibility"}</span>{" Quick View\n            "}</button></div><div className="p-space-lg flex flex-col flex-1"><div className="flex items-center justify-between text-outline font-label-sm text-label-sm uppercase tracking-wider mb-1"><span>{"Aster Horology"}</span><span>{"Ref. AT-04-NOCT"}</span></div><h3 className="font-headline-sm text-headline-sm font-bold text-on-surface mb-space-xs group-hover:text-primary transition-colors">{"\n              Aster No.04 Automatic — Midnight Edition\n            "}</h3><p className="font-body-sm text-body-sm text-on-surface-variant line-clamp-2 mb-space-md">{"\n              Deep matte black dial paired with brushed DLC carbon casing. Skeletonized sapphire exhibition caseback displaying precision rotor.\n            "}</p><div className="grid grid-cols-3 gap-2 py-2 px-3 bg-surface-container-low rounded-lg mb-space-md font-label-sm text-label-sm"><div><span className="text-outline block uppercase">{"Calibre"}</span><span className="font-bold text-on-surface">{"Auto 28.8k"}</span></div><div><span className="text-outline block uppercase">{"Power"}</span><span className="font-bold text-on-surface">{"38 Hours"}</span></div><div><span className="text-outline block uppercase">{"Depth"}</span><span className="font-bold text-on-surface">{"100m ATM"}</span></div></div><div className="mt-auto pt-space-sm flex items-center justify-between gap-space-md"><div className="flex flex-col"><span className="font-label-sm text-label-sm text-outline uppercase tracking-wider">{"Atelier Value"}</span><span className="font-headline-md text-headline-md font-bold text-primary">{"₹18,990"}</span></div><button type="button" className="h-11 px-space-md rounded bg-tertiary-container text-tertiary-fixed hover:bg-tertiary hover:text-surface-container-lowest font-label-md text-label-md uppercase tracking-wider transition-colors flex items-center gap-2" onClick={() => ui.addCart("Aster No.04 Automatic")}><span className="material-symbols-outlined text-[18px]">{"shopping_bag"}</span>{"\n                Acquire\n              "}</button></div></div></motion.article><motion.article className={ui.productClass("bg-surface-container-lowest rounded-xl shadow-sm hover:shadow-xl transition-all duration-300 flex flex-col group overflow-hidden", "Kairo Chronograph 42 — Matte DLC", "Flyback Chrono Meca-Quartz VK64 favorite timer 1/5th Sec Sweep visibility Quick View Kairo Atelier Ref. KC-42-DLC Kairo Chronograph 42 — Matte DLC Bi-compax dark tactical dial with instant zero-reset flyback chronograph module and tachymeter chapter ring. Movement VK64 Hybrid Crystal AR Sapphire Chrono 60 Min Sub Atelier Value ₹12,990 shopping_bag Acquire", "", "")} style={{
      order: ui.sortOrder(12990, 2)
    }} whileHover={{
      y: -4
    }} transition={{
      type: "spring",
      stiffness: 300,
      damping: 26
    }} data-product-link="true" role="link" tabIndex={0}><div className="relative bg-surface-container-low p-space-lg flex items-center justify-center min-h-[320px] overflow-hidden"><div className="absolute top-space-md left-space-md flex flex-col gap-1 z-10"><span className="px-2.5 py-0.5 rounded bg-primary text-secondary-fixed font-label-sm text-label-sm uppercase tracking-wider">{"Flyback Chrono"}</span><span className="px-2 py-0.5 rounded bg-surface-container-lowest text-on-surface-variant font-label-sm text-label-sm uppercase tracking-wider shadow-sm">{"Meca-Quartz VK64"}</span></div><button type="button" aria-label="Save to Vault" className="absolute top-space-md right-space-md w-9 h-9 rounded-full bg-surface-container-lowest/80 backdrop-blur-sm text-on-surface-variant hover:text-error hover:bg-surface-container-lowest flex items-center justify-center transition-all z-10 shadow-sm" onClick={() => ui.toggleWishlist("Kairo Chronograph 42 — Matte DLC")}><span className="material-symbols-outlined text-[20px]">{"favorite"}</span></button><img className="w-64 h-64 object-contain group-hover:scale-105 transition-transform duration-500" alt="Kairo Chronograph 42 luxury watch, matte DLC black case, dark charcoal bi-compax sub dials, champagne accents on seconds hand, black sailcloth strap, studio macro horology photography on crisp clean backdrop." data-alt="Kairo Chronograph 42 luxury watch, matte DLC black case, dark charcoal bi-compax sub dials, champagne accents on seconds hand, black sailcloth strap, studio macro horology photography on crisp clean backdrop." src="https://lh3.googleusercontent.com/aida-public/AB6AXuDXJMIulLmp42HD-IkzImLShmn18hKKVdZVYz41I210DxclMLWV_cJNF_qSPctFU9YfseGY2QLGd0PezKaBixlPPyUV4MgoZ2enWMUpblVieNnKBOoo7BHewqLGACrceLBrXQ8-lVbV1MzITzyoCVad-yyRSZKU-mdq4Q8uF2QTBqorNixiZ60lr1iaPXsTVQHkfweqxIudMGoxlsfUET2nFRvayyVla4EgPGOySbX65Y-b6ZkCXWXW" /><div className="absolute bottom-space-md left-space-md px-2 py-1 rounded bg-primary/90 text-tertiary-fixed font-label-sm text-label-sm uppercase flex items-center gap-1"><span className="material-symbols-outlined text-[13px]">{"timer"}</span>{"\n              1/5th Sec Sweep\n            "}</div><button type="button" className="absolute bottom-space-md right-space-md h-8 px-space-sm rounded bg-surface-container-lowest/90 backdrop-blur-sm hover:bg-primary hover:text-surface-container-lowest font-label-sm text-label-sm uppercase tracking-wider transition-all flex items-center gap-1 shadow-sm" onClick={() => ui.openQuickView({
          "title": "Kairo Chronograph 42",
          "price": "₹12,990",
          "series": "Matte DLC",
          "specs": "Seiko VK64 Meca-Quartz • 42mm Matte Black Case • Tachymeter",
          "image": "https://lh3.googleusercontent.com/aida-public/AB6AXuDXJMIulLmp42HD-IkzImLShmn18hKKVdZVYz41I210DxclMLWV_cJNF_qSPctFU9YfseGY2QLGd0PezKaBixlPPyUV4MgoZ2enWMUpblVieNnKBOoo7BHewqLGACrceLBrXQ8-lVbV1MzITzyoCVad-yyRSZKU-mdq4Q8uF2QTBqorNixiZ60lr1iaPXsTVQHkfweqxIudMGoxlsfUET2nFRvayyVla4EgPGOySbX65Y-b6ZkCXWXW"
        })}><span className="material-symbols-outlined text-[15px]">{"visibility"}</span>{" Quick View\n            "}</button></div><div className="p-space-lg flex flex-col flex-1"><div className="flex items-center justify-between text-outline font-label-sm text-label-sm uppercase tracking-wider mb-1"><span>{"Kairo Atelier"}</span><span>{"Ref. KC-42-DLC"}</span></div><h3 className="font-headline-sm text-headline-sm font-bold text-on-surface mb-space-xs group-hover:text-primary transition-colors">{"\n              Kairo Chronograph 42 — Matte DLC\n            "}</h3><p className="font-body-sm text-body-sm text-on-surface-variant line-clamp-2 mb-space-md">{"\n              Bi-compax dark tactical dial with instant zero-reset flyback chronograph module and tachymeter chapter ring.\n            "}</p><div className="grid grid-cols-3 gap-2 py-2 px-3 bg-surface-container-low rounded-lg mb-space-md font-label-sm text-label-sm"><div><span className="text-outline block uppercase">{"Movement"}</span><span className="font-bold text-on-surface">{"VK64 Hybrid"}</span></div><div><span className="text-outline block uppercase">{"Crystal"}</span><span className="font-bold text-on-surface">{"AR Sapphire"}</span></div><div><span className="text-outline block uppercase">{"Chrono"}</span><span className="font-bold text-on-surface">{"60 Min Sub"}</span></div></div><div className="mt-auto pt-space-sm flex items-center justify-between gap-space-md"><div className="flex flex-col"><span className="font-label-sm text-label-sm text-outline uppercase tracking-wider">{"Atelier Value"}</span><span className="font-headline-md text-headline-md font-bold text-primary">{"₹12,990"}</span></div><button type="button" className="h-11 px-space-md rounded bg-tertiary-container text-tertiary-fixed hover:bg-tertiary hover:text-surface-container-lowest font-label-md text-label-md uppercase tracking-wider transition-colors flex items-center gap-2" onClick={() => ui.addCart("Kairo Chronograph 42")}><span className="material-symbols-outlined text-[18px]">{"shopping_bag"}</span>{"\n                Acquire\n              "}</button></div></div></motion.article><motion.article className={ui.productClass("bg-surface-container-lowest rounded-xl shadow-sm hover:shadow-xl transition-all duration-300 flex flex-col group overflow-hidden", "Atlas S4 Dual GPS — Stealth Titanium", "Stealth Titanium Grade 5 Aerospace favorite explore Dual L1/L5 GPS visibility Quick View Atlas Instruments Ref. AT-S4-TITAN Atlas S4 Dual GPS — Stealth Titanium Engineered from monolithic Grade 5 Titanium with carbon-vapour coating. Dual-band satellite acquisition with ambient barometer. Casing 43mm Gr.5 Weight 54 Grams Battery 14 Days Atelier Value ₹13,990 shopping_bag Acquire", "", "")} style={{
      order: ui.sortOrder(13990, 3)
    }} whileHover={{
      y: -4
    }} transition={{
      type: "spring",
      stiffness: 300,
      damping: 26
    }} data-product-link="true" role="link" tabIndex={0}><div className="relative bg-surface-container-low p-space-lg flex items-center justify-center min-h-[320px] overflow-hidden"><div className="absolute top-space-md left-space-md flex flex-col gap-1 z-10"><span className="px-2.5 py-0.5 rounded bg-primary text-secondary-fixed font-label-sm text-label-sm uppercase tracking-wider">{"Stealth Titanium"}</span><span className="px-2 py-0.5 rounded bg-surface-container-lowest text-on-surface-variant font-label-sm text-label-sm uppercase tracking-wider shadow-sm">{"Grade 5 Aerospace"}</span></div><button type="button" aria-label="Save to Vault" className="absolute top-space-md right-space-md w-9 h-9 rounded-full bg-surface-container-lowest/80 backdrop-blur-sm text-on-surface-variant hover:text-error hover:bg-surface-container-lowest flex items-center justify-center transition-all z-10 shadow-sm" onClick={() => ui.toggleWishlist("Atlas S4 Dual GPS — Stealth Titanium")}><span className="material-symbols-outlined text-[20px]">{"favorite"}</span></button><img className="w-64 h-64 object-contain group-hover:scale-105 transition-transform duration-500" alt="Atlas S4 Dual GPS watch, stealth matte black sandblasted titanium bezel, dark high contrast hybrid dial, textured black FKM fluoroelastomer band, architectural minimalist horology studio lighting, white backdrop." data-alt="Atlas S4 Dual GPS watch, stealth matte black sandblasted titanium bezel, dark high contrast hybrid dial, textured black FKM fluoroelastomer band, architectural minimalist horology studio lighting, white backdrop." src="https://lh3.googleusercontent.com/aida-public/AB6AXuCcytJb_4RqqoZXv4P_ky4Z8PLtnixmZzmdUlpGXiAYpoKSrBPKawEWF6cmS3f23MOcdBuXznRVsMDLNN1rADxoUjLRlGzViskgQz65dYBMFjCN3-KqcSdEKWme8qyRu06KgXUaFtsbNk-udllegS_KjE4TLnSWKi0QR0R06bn8re68AokxqMKWFkG1-NfkW0lvUdFj5lUw84rFILP8ZXXEtTBr5XgZkuFkAMwGsCyIZWylmz5feM0C" /><div className="absolute bottom-space-md left-space-md px-2 py-1 rounded bg-primary/90 text-tertiary-fixed font-label-sm text-label-sm uppercase flex items-center gap-1"><span className="material-symbols-outlined text-[13px]">{"explore"}</span>{"\n              Dual L1/L5 GPS\n            "}</div><button type="button" className="absolute bottom-space-md right-space-md h-8 px-space-sm rounded bg-surface-container-lowest/90 backdrop-blur-sm hover:bg-primary hover:text-surface-container-lowest font-label-sm text-label-sm uppercase tracking-wider transition-all flex items-center gap-1 shadow-sm" onClick={() => ui.openQuickView({
          "title": "Atlas S4 Dual GPS",
          "price": "₹13,990",
          "series": "Stealth Titanium",
          "specs": "Grade 5 Titanium • Dual-Frequency GNSS • 14-Day Battery",
          "image": "https://lh3.googleusercontent.com/aida-public/AB6AXuCcytJb_4RqqoZXv4P_ky4Z8PLtnixmZzmdUlpGXiAYpoKSrBPKawEWF6cmS3f23MOcdBuXznRVsMDLNN1rADxoUjLRlGzViskgQz65dYBMFjCN3-KqcSdEKWme8qyRu06KgXUaFtsbNk-udllegS_KjE4TLnSWKi0QR0R06bn8re68AokxqMKWFkG1-NfkW0lvUdFj5lUw84rFILP8ZXXEtTBr5XgZkuFkAMwGsCyIZWylmz5feM0C"
        })}><span className="material-symbols-outlined text-[15px]">{"visibility"}</span>{" Quick View\n            "}</button></div><div className="p-space-lg flex flex-col flex-1"><div className="flex items-center justify-between text-outline font-label-sm text-label-sm uppercase tracking-wider mb-1"><span>{"Atlas Instruments"}</span><span>{"Ref. AT-S4-TITAN"}</span></div><h3 className="font-headline-sm text-headline-sm font-bold text-on-surface mb-space-xs group-hover:text-primary transition-colors">{"\n              Atlas S4 Dual GPS — Stealth Titanium\n            "}</h3><p className="font-body-sm text-body-sm text-on-surface-variant line-clamp-2 mb-space-md">{"\n              Engineered from monolithic Grade 5 Titanium with carbon-vapour coating. Dual-band satellite acquisition with ambient barometer.\n            "}</p><div className="grid grid-cols-3 gap-2 py-2 px-3 bg-surface-container-low rounded-lg mb-space-md font-label-sm text-label-sm"><div><span className="text-outline block uppercase">{"Casing"}</span><span className="font-bold text-on-surface">{"43mm Gr.5"}</span></div><div><span className="text-outline block uppercase">{"Weight"}</span><span className="font-bold text-on-surface">{"54 Grams"}</span></div><div><span className="text-outline block uppercase">{"Battery"}</span><span className="font-bold text-on-surface">{"14 Days"}</span></div></div><div className="mt-auto pt-space-sm flex items-center justify-between gap-space-md"><div className="flex flex-col"><span className="font-label-sm text-label-sm text-outline uppercase tracking-wider">{"Atelier Value"}</span><span className="font-headline-md text-headline-md font-bold text-primary">{"₹13,990"}</span></div><button type="button" className="h-11 px-space-md rounded bg-tertiary-container text-tertiary-fixed hover:bg-tertiary hover:text-surface-container-lowest font-label-md text-label-md uppercase tracking-wider transition-colors flex items-center gap-2" onClick={() => ui.addCart("Atlas S4 Dual GPS")}><span className="material-symbols-outlined text-[18px]">{"shopping_bag"}</span>{"\n                Acquire\n              "}</button></div></div></motion.article><motion.article className={ui.productClass("bg-surface-container-lowest rounded-xl shadow-sm hover:shadow-xl transition-all duration-300 flex flex-col group overflow-hidden", "Pulse One AMOLED — Carbon Black", "OLED Horizon 1,000 Nits Brightness favorite favorite ECG & SpO2 Sensor visibility Quick View Pulse Digital Lab Ref. PL-01-CRB Pulse One AMOLED — Carbon Black Always-on infinite-contrast AMOLED panel encased in satin carbon. Dedicated mechanical haptic escapement crown. Screen 1.43\" OLED Sensor 8-PD Optic Chassis Ceramic Cap Atelier Value ₹16,490 shopping_bag Acquire", "", "")} style={{
      order: ui.sortOrder(16490, 4)
    }} whileHover={{
      y: -4
    }} transition={{
      type: "spring",
      stiffness: 300,
      damping: 26
    }} data-product-link="true" role="link" tabIndex={0}><div className="relative bg-surface-container-low p-space-lg flex items-center justify-center min-h-[320px] overflow-hidden"><div className="absolute top-space-md left-space-md flex flex-col gap-1 z-10"><span className="px-2.5 py-0.5 rounded bg-primary text-secondary-fixed font-label-sm text-label-sm uppercase tracking-wider">{"OLED Horizon"}</span><span className="px-2 py-0.5 rounded bg-surface-container-lowest text-on-surface-variant font-label-sm text-label-sm uppercase tracking-wider shadow-sm">{"1,000 Nits Brightness"}</span></div><button type="button" aria-label="Save to Vault" className="absolute top-space-md right-space-md w-9 h-9 rounded-full bg-surface-container-lowest/80 backdrop-blur-sm text-on-surface-variant hover:text-error hover:bg-surface-container-lowest flex items-center justify-center transition-all z-10 shadow-sm" onClick={() => ui.toggleWishlist("Pulse One AMOLED — Carbon Black")}><span className="material-symbols-outlined text-[20px]">{"favorite"}</span></button><img className="w-64 h-64 object-contain group-hover:scale-105 transition-transform duration-500" alt="Pulse One AMOLED smartwatch, jet black carbon casing, deep black screen displaying a minimal illuminated analog watch face with champagne markers, black linked steel mesh bracelet, luxury tech product photography, isolated on white." data-alt="Pulse One AMOLED smartwatch, jet black carbon casing, deep black screen displaying a minimal illuminated analog watch face with champagne markers, black linked steel mesh bracelet, luxury tech product photography, isolated on white." src="https://lh3.googleusercontent.com/aida-public/AB6AXuANsRMzVjXALDZ2dYM-bSStQ1CDZ-wiWoueWcxhKetWj_PvpmqHPOH35tmObLQIKvbZHELN2nXfSh1htuaoMN3fLatplVflA-RmZgSGLuI336IZ1X_8j9KS_yrZf7dny5gURxVA4YtN0Y--gTLFra0WjTEzJA3gpzw97JJlE3_ToxaBRCdSv_9L6kQXvmessYVHMkOlRX0HlYSfPO-xQxl3a_YjF-4a0pnVKoQ-4xdgTxw9hE3o_pVw" /><div className="absolute bottom-space-md left-space-md px-2 py-1 rounded bg-primary/90 text-tertiary-fixed font-label-sm text-label-sm uppercase flex items-center gap-1"><span className="material-symbols-outlined text-[13px]">{"favorite"}</span>{"\n              ECG & SpO2 Sensor\n            "}</div><button type="button" className="absolute bottom-space-md right-space-md h-8 px-space-sm rounded bg-surface-container-lowest/90 backdrop-blur-sm hover:bg-primary hover:text-surface-container-lowest font-label-sm text-label-sm uppercase tracking-wider transition-all flex items-center gap-1 shadow-sm" onClick={() => ui.openQuickView({
          "title": "Pulse One AMOLED",
          "price": "₹16,490",
          "series": "Carbon Black",
          "specs": "Custom True-Black AMOLED • 44mm Anodized Casing • Bio-Sense Core",
          "image": "https://lh3.googleusercontent.com/aida-public/AB6AXuANsRMzVjXALDZ2dYM-bSStQ1CDZ-wiWoueWcxhKetWj_PvpmqHPOH35tmObLQIKvbZHELN2nXfSh1htuaoMN3fLatplVflA-RmZgSGLuI336IZ1X_8j9KS_yrZf7dny5gURxVA4YtN0Y--gTLFra0WjTEzJA3gpzw97JJlE3_ToxaBRCdSv_9L6kQXvmessYVHMkOlRX0HlYSfPO-xQxl3a_YjF-4a0pnVKoQ-4xdgTxw9hE3o_pVw"
        })}><span className="material-symbols-outlined text-[15px]">{"visibility"}</span>{" Quick View\n            "}</button></div><div className="p-space-lg flex flex-col flex-1"><div className="flex items-center justify-between text-outline font-label-sm text-label-sm uppercase tracking-wider mb-1"><span>{"Pulse Digital Lab"}</span><span>{"Ref. PL-01-CRB"}</span></div><h3 className="font-headline-sm text-headline-sm font-bold text-on-surface mb-space-xs group-hover:text-primary transition-colors">{"\n              Pulse One AMOLED — Carbon Black\n            "}</h3><p className="font-body-sm text-body-sm text-on-surface-variant line-clamp-2 mb-space-md">{"\n              Always-on infinite-contrast AMOLED panel encased in satin carbon. Dedicated mechanical haptic escapement crown.\n            "}</p><div className="grid grid-cols-3 gap-2 py-2 px-3 bg-surface-container-low rounded-lg mb-space-md font-label-sm text-label-sm"><div><span className="text-outline block uppercase">{"Screen"}</span><span className="font-bold text-on-surface">{"1.43\" OLED"}</span></div><div><span className="text-outline block uppercase">{"Sensor"}</span><span className="font-bold text-on-surface">{"8-PD Optic"}</span></div><div><span className="text-outline block uppercase">{"Chassis"}</span><span className="font-bold text-on-surface">{"Ceramic Cap"}</span></div></div><div className="mt-auto pt-space-sm flex items-center justify-between gap-space-md"><div className="flex flex-col"><span className="font-label-sm text-label-sm text-outline uppercase tracking-wider">{"Atelier Value"}</span><span className="font-headline-md text-headline-md font-bold text-primary">{"₹16,490"}</span></div><button type="button" className="h-11 px-space-md rounded bg-tertiary-container text-tertiary-fixed hover:bg-tertiary hover:text-surface-container-lowest font-label-md text-label-md uppercase tracking-wider transition-colors flex items-center gap-2" onClick={() => ui.addCart("Pulse One AMOLED")}><span className="material-symbols-outlined text-[18px]">{"shopping_bag"}</span>{"\n                Acquire\n              "}</button></div></div></motion.article><motion.article className={ui.productClass("bg-surface-container-lowest rounded-xl shadow-sm hover:shadow-xl transition-all duration-300 flex flex-col group overflow-hidden", "Heritage Field 40 — Night Ops", "Tactical Field High-Inertia Balance favorite military_tech Anti-Magnetic 4800A/m visibility Quick View Heritage Mil-Spec Ref. HF-40-OPS Heritage Field 40 — Night Ops Nocturnal tactical reference with non-reflective matte bead-blasted treatment. High-contrast syringe hands with tritium indices. Calibre Manual 21.6k Case 40mm Bead Shield Faraday Cage Atelier Value ₹14,290 shopping_bag Acquire", "", "")} style={{
      order: ui.sortOrder(14290, 5)
    }} whileHover={{
      y: -4
    }} transition={{
      type: "spring",
      stiffness: 300,
      damping: 26
    }} data-product-link="true" role="link" tabIndex={0}><div className="relative bg-surface-container-low p-space-lg flex items-center justify-center min-h-[320px] overflow-hidden"><div className="absolute top-space-md left-space-md flex flex-col gap-1 z-10"><span className="px-2.5 py-0.5 rounded bg-primary text-secondary-fixed font-label-sm text-label-sm uppercase tracking-wider">{"Tactical Field"}</span><span className="px-2 py-0.5 rounded bg-surface-container-lowest text-on-surface-variant font-label-sm text-label-sm uppercase tracking-wider shadow-sm">{"High-Inertia Balance"}</span></div><button type="button" aria-label="Save to Vault" className="absolute top-space-md right-space-md w-9 h-9 rounded-full bg-surface-container-lowest/80 backdrop-blur-sm text-on-surface-variant hover:text-error hover:bg-surface-container-lowest flex items-center justify-center transition-all z-10 shadow-sm" onClick={() => ui.toggleWishlist("Heritage Field 40 — Night Ops")}><span className="material-symbols-outlined text-[20px]">{"favorite"}</span></button><img className="w-64 h-64 object-contain group-hover:scale-105 transition-transform duration-500" alt="Heritage Field 40 tactical watch, stealth night ops edition, matte black non-reflective case, stark white indices, olive drab ballistic nylon nato strap, black gunmetal hardware, studio horology capture on white backdrop." data-alt="Heritage Field 40 tactical watch, stealth night ops edition, matte black non-reflective case, stark white indices, olive drab ballistic nylon nato strap, black gunmetal hardware, studio horology capture on white backdrop." src="https://lh3.googleusercontent.com/aida-public/AB6AXuAyGMcBHFl_KIKDRep2egM_t69hN0VWQ1cAWGGEfaaiN2gwIKjMAH4kxzpFRu6KoauAzlMpvgKZPwQEs4cEGdewHlgfAO5jHNXhMuZKz3YWKn4T4hdMth93hTCtnLbbUfEXXFDLCoLYxs-HMUsKrXUwij8pEEYDGsY-V9Ivnx1jYBrjdRu7X5ti3anvZbTpmHWaO7GT98bBbknl0qMppvCboh0zPgvRffrEwJC2S5dy8E0JUqTSonUw" /><div className="absolute bottom-space-md left-space-md px-2 py-1 rounded bg-primary/90 text-tertiary-fixed font-label-sm text-label-sm uppercase flex items-center gap-1"><span className="material-symbols-outlined text-[13px]">{"military_tech"}</span>{"\n              Anti-Magnetic 4800A/m\n            "}</div><button type="button" className="absolute bottom-space-md right-space-md h-8 px-space-sm rounded bg-surface-container-lowest/90 backdrop-blur-sm hover:bg-primary hover:text-surface-container-lowest font-label-sm text-label-sm uppercase tracking-wider transition-all flex items-center gap-1 shadow-sm" onClick={() => ui.openQuickView({
          "title": "Heritage Field 40",
          "price": "₹14,290",
          "series": "Night Ops",
          "specs": "Manual Wind Calibre • 40mm Matte Casing • 100m Field Grade",
          "image": "https://lh3.googleusercontent.com/aida-public/AB6AXuAyGMcBHFl_KIKDRep2egM_t69hN0VWQ1cAWGGEfaaiN2gwIKjMAH4kxzpFRu6KoauAzlMpvgKZPwQEs4cEGdewHlgfAO5jHNXhMuZKz3YWKn4T4hdMth93hTCtnLbbUfEXXFDLCoLYxs-HMUsKrXUwij8pEEYDGsY-V9Ivnx1jYBrjdRu7X5ti3anvZbTpmHWaO7GT98bBbknl0qMppvCboh0zPgvRffrEwJC2S5dy8E0JUqTSonUw"
        })}><span className="material-symbols-outlined text-[15px]">{"visibility"}</span>{" Quick View\n            "}</button></div><div className="p-space-lg flex flex-col flex-1"><div className="flex items-center justify-between text-outline font-label-sm text-label-sm uppercase tracking-wider mb-1"><span>{"Heritage Mil-Spec"}</span><span>{"Ref. HF-40-OPS"}</span></div><h3 className="font-headline-sm text-headline-sm font-bold text-on-surface mb-space-xs group-hover:text-primary transition-colors">{"\n              Heritage Field 40 — Night Ops\n            "}</h3><p className="font-body-sm text-body-sm text-on-surface-variant line-clamp-2 mb-space-md">{"\n              Nocturnal tactical reference with non-reflective matte bead-blasted treatment. High-contrast syringe hands with tritium indices.\n            "}</p><div className="grid grid-cols-3 gap-2 py-2 px-3 bg-surface-container-low rounded-lg mb-space-md font-label-sm text-label-sm"><div><span className="text-outline block uppercase">{"Calibre"}</span><span className="font-bold text-on-surface">{"Manual 21.6k"}</span></div><div><span className="text-outline block uppercase">{"Case"}</span><span className="font-bold text-on-surface">{"40mm Bead"}</span></div><div><span className="text-outline block uppercase">{"Shield"}</span><span className="font-bold text-on-surface">{"Faraday Cage"}</span></div></div><div className="mt-auto pt-space-sm flex items-center justify-between gap-space-md"><div className="flex flex-col"><span className="font-label-sm text-label-sm text-outline uppercase tracking-wider">{"Atelier Value"}</span><span className="font-headline-md text-headline-md font-bold text-primary">{"₹14,290"}</span></div><button type="button" className="h-11 px-space-md rounded bg-tertiary-container text-tertiary-fixed hover:bg-tertiary hover:text-surface-container-lowest font-label-md text-label-md uppercase tracking-wider transition-colors flex items-center gap-2" onClick={() => ui.addCart("Heritage Field 40")}><span className="material-symbols-outlined text-[18px]">{"shopping_bag"}</span>{"\n                Acquire\n              "}</button></div></div></motion.article><motion.article className={ui.productClass("bg-surface-container-lowest rounded-xl shadow-sm hover:shadow-xl transition-all duration-300 flex flex-col group overflow-hidden", "Voyager GMT 41 — Batman Bezel", "Only 2 Vault Allocations Dual-Time Horizon favorite public Independent GMT Hand visibility Quick View Voyager Genève Ref. VG-41-GMT Voyager GMT 41 — Batman Bezel Split bi-color ceramic 24-hour bezel in midnight black and oceanic blue. Quickset flyer GMT complication with jumping local hour. Calibre Miyota 9075 Bezel Zirconia Cer. Depth 200m Diver Atelier Value ₹25,990 shopping_bag Acquire", "", "")} style={{
      order: ui.sortOrder(25990, 6)
    }} whileHover={{
      y: -4
    }} transition={{
      type: "spring",
      stiffness: 300,
      damping: 26
    }} data-product-link="true" role="link" tabIndex={0}><div className="relative bg-surface-container-low p-space-lg flex items-center justify-center min-h-[320px] overflow-hidden"><div className="absolute top-space-md left-space-md flex flex-col gap-1 z-10"><span className="px-2.5 py-0.5 rounded bg-error text-surface-container-lowest font-label-sm text-label-sm uppercase tracking-wider">{"Only 2 Vault Allocations"}</span><span className="px-2 py-0.5 rounded bg-surface-container-lowest text-on-surface-variant font-label-sm text-label-sm uppercase tracking-wider shadow-sm">{"Dual-Time Horizon"}</span></div><button type="button" aria-label="Save to Vault" className="absolute top-space-md right-space-md w-9 h-9 rounded-full bg-surface-container-lowest/80 backdrop-blur-sm text-on-surface-variant hover:text-error hover:bg-surface-container-lowest flex items-center justify-center transition-all z-10 shadow-sm" onClick={() => ui.toggleWishlist("Voyager GMT 41 — Batman Bezel")}><span className="material-symbols-outlined text-[20px]">{"favorite"}</span></button><img className="w-64 h-64 object-contain group-hover:scale-105 transition-transform duration-500" alt="Voyager GMT 41 luxury travel watch, black and deep midnight blue split ceramic bezel, jet black dial, bold cyan GMT second timezone hand, 5-link jubilee style steel bracelet, ultra sharp studio lighting, white backdrop." data-alt="Voyager GMT 41 luxury travel watch, black and deep midnight blue split ceramic bezel, jet black dial, bold cyan GMT second timezone hand, 5-link jubilee style steel bracelet, ultra sharp studio lighting, white backdrop." src="https://lh3.googleusercontent.com/aida-public/AB6AXuDv5_6TeNsPGOTEWlpbZDbGwVYDCpx7q5lW1r458AEki6fRMO_9_70OybCbUV52vpK5YWnNIRWeBeKu0G14Na-r5SdlRGYxCpKAVrSfdABNnCwpl0CGFxVh3qQR9XScPZEdQF3RIfIqQm5eWHgVZQ0fV6ZvpBy8kqD57uB9PYlAkU8bJJEf3YrJq2lQ0HztC6b529_TuBsdrUHYe-V35W_SJwo4BvQfXFLjUueQ6LR6vuuO3MdwHebs" /><div className="absolute bottom-space-md left-space-md px-2 py-1 rounded bg-primary/90 text-secondary-fixed font-label-sm text-label-sm uppercase flex items-center gap-1"><span className="material-symbols-outlined text-[13px]">{"public"}</span>{"\n              Independent GMT Hand\n            "}</div><button type="button" className="absolute bottom-space-md right-space-md h-8 px-space-sm rounded bg-surface-container-lowest/90 backdrop-blur-sm hover:bg-primary hover:text-surface-container-lowest font-label-sm text-label-sm uppercase tracking-wider transition-all flex items-center gap-1 shadow-sm" onClick={() => ui.openQuickView({
          "title": "Voyager GMT 41",
          "price": "₹25,990",
          "series": "Batman Bezel",
          "specs": "True GMT Automatic • 41mm Ceramic Bezel • Jubilee Steel",
          "image": "https://lh3.googleusercontent.com/aida-public/AB6AXuDv5_6TeNsPGOTEWlpbZDbGwVYDCpx7q5lW1r458AEki6fRMO_9_70OybCbUV52vpK5YWnNIRWeBeKu0G14Na-r5SdlRGYxCpKAVrSfdABNnCwpl0CGFxVh3qQR9XScPZEdQF3RIfIqQm5eWHgVZQ0fV6ZvpBy8kqD57uB9PYlAkU8bJJEf3YrJq2lQ0HztC6b529_TuBsdrUHYe-V35W_SJwo4BvQfXFLjUueQ6LR6vuuO3MdwHebs"
        })}><span className="material-symbols-outlined text-[15px]">{"visibility"}</span>{" Quick View\n            "}</button></div><div className="p-space-lg flex flex-col flex-1"><div className="flex items-center justify-between text-outline font-label-sm text-label-sm uppercase tracking-wider mb-1"><span>{"Voyager Genève"}</span><span>{"Ref. VG-41-GMT"}</span></div><h3 className="font-headline-sm text-headline-sm font-bold text-on-surface mb-space-xs group-hover:text-primary transition-colors">{"\n              Voyager GMT 41 — Batman Bezel\n            "}</h3><p className="font-body-sm text-body-sm text-on-surface-variant line-clamp-2 mb-space-md">{"\n              Split bi-color ceramic 24-hour bezel in midnight black and oceanic blue. Quickset flyer GMT complication with jumping local hour.\n            "}</p><div className="grid grid-cols-3 gap-2 py-2 px-3 bg-surface-container-low rounded-lg mb-space-md font-label-sm text-label-sm"><div><span className="text-outline block uppercase">{"Calibre"}</span><span className="font-bold text-on-surface">{"Miyota 9075"}</span></div><div><span className="text-outline block uppercase">{"Bezel"}</span><span className="font-bold text-on-surface">{"Zirconia Cer."}</span></div><div><span className="text-outline block uppercase">{"Depth"}</span><span className="font-bold text-on-surface">{"200m Diver"}</span></div></div><div className="mt-auto pt-space-sm flex items-center justify-between gap-space-md"><div className="flex flex-col"><span className="font-label-sm text-label-sm text-outline uppercase tracking-wider">{"Atelier Value"}</span><span className="font-headline-md text-headline-md font-bold text-primary">{"₹25,990"}</span></div><button type="button" className="h-11 px-space-md rounded bg-tertiary-container text-tertiary-fixed hover:bg-tertiary hover:text-surface-container-lowest font-label-md text-label-md uppercase tracking-wider transition-colors flex items-center gap-2" onClick={() => ui.addCart("Voyager GMT 41")}><span className="material-symbols-outlined text-[18px]">{"shopping_bag"}</span>{"\n                Acquire\n              "}</button></div></div></motion.article></RevealSection>;
}
