import { useProduct } from "../../state/ProductContext.jsx";
import RevealSection from "../../components/RevealSection.jsx";
import { motion } from "motion/react";
import Section01AsterNo04Automatic from "./Section01AsterNo04Automatic.jsx";
import Section02CompleteHorologicalSpecifications from "./Section02CompleteHorologicalSpecifications.jsx";
import Section03CalibreBuildComparisonMatrix from "./Section03CalibreBuildComparisonMatrix.jsx";
import Section04TechnicalFieldReferenceFaqs from "./Section04TechnicalFieldReferenceFaqs.jsx";
import Section05SimilarHorologicalPieces from "./Section05SimilarHorologicalPieces.jsx";
export default function Design2() {
 const ui=useProduct();
 return (<main className="w-full pt-24 sm:pt-28 bg-surface min-h-screen" id="main-content"><div className="flex flex-col w-full"><div className="w-full bg-surface-container-low py-space-sm px-margin-mobile lg:px-margin"><div className="max-w-7xl mx-auto flex flex-wrap items-center justify-between gap-space-sm"><nav aria-label="Breadcrumb" className="flex items-center gap-space-xs font-label-sm text-label-sm tracking-wider uppercase text-on-surface-variant"><a className="hover:text-primary transition-colors" href="#" onClick={e => {e.preventDefault(); ui.notify("Home — link preview only");}}>{"Home"}</a><span className="text-outline">{"/"}</span><a className="hover:text-primary transition-colors" href="#" onClick={e => {e.preventDefault(); ui.notify("Automatic Watches — link preview only");}}>{"Automatic Watches"}</a><span className="text-outline">{"/"}</span><a className="hover:text-primary transition-colors" href="#" onClick={e => {e.preventDefault(); ui.notify("Aster No.04 Automatic — link preview only");}}>{"Aster No.04 Automatic"}</a><span className="text-outline">{"/"}</span><span className="text-primary font-bold">{"Technical Console"}</span></nav><div className="flex items-center gap-space-md"><span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded bg-surface text-on-surface font-label-sm text-label-sm uppercase tracking-widest shadow-sm"><span className="w-1.5 h-1.5 rounded-full bg-tertiary-fixed-variant animate-pulse"></span>{"\n          Escapement Calibrated: ±3 sec/day\n        "}</span><span className="hidden sm:inline-block font-label-sm text-label-sm text-outline-variant">{"|"}</span><span className="hidden sm:inline-flex items-center gap-1 font-label-sm text-label-sm text-on-surface-variant tracking-wider uppercase"><span className="material-symbols-outlined text-[14px] text-secondary">{"verified_user"}</span>{" Certified Batch Archive\n        "}</span></div></div></div><Section01AsterNo04Automatic /><Section02CompleteHorologicalSpecifications /><Section03CalibreBuildComparisonMatrix /><Section04TechnicalFieldReferenceFaqs /><Section05SimilarHorologicalPieces /></div></main>);
}
